Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -32,6 +32,31 @@ jobs:
         run: |
           ROOT_DIR="."
           OUTPUT_DIR="./charts/packages"
+          
+          echo "Testing each package...."
+          find "$ROOT_DIR" -name "Chart.yaml" -print0 | while IFS= read -r -d '' chart; do
+            chart_dir=$(dirname "$chart")
+            echo "Processing chart directory: $chart_dir"
+            # Try block (Bash equivalent)
+        
+            result=$(helm template "$chart_dir" 2>&1)  # Capture stderr and stdout
+            if [ $? -ne 0 ]; then
+            # If the command failed, print the error message and exit the script
+              echo "Error executing helm template for chart $chart_dir:"
+              echo "$result"  # Output the error message
+              test_failed=true
+              exit 1  # Exit the script with a non-zero status to indicate failure
+            else
+           # If the command was successful, print the result
+              echo "Helm template output for $chart_dir:"
+              echo "$result"
+           fi
+          done
+
+          if ["$test_failed"=true]; then
+             echo "Exiting due to failure in helm template test."
+             exit 1
+          fi
 
           # Create the output directory if it doesn't exist
           mkdir -p "$OUTPUT_DIR"
